// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gihloijdfswvfvlydcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpaGxvaWpkZnN3dmZ2bHlkY3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODU1OTcsImV4cCI6MjA2Mzg2MTU5N30.bhZRl1ClYD9G78aAz2gHLItNMdI8h9mo7Fn0WmpE_pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);